# Forretningsobjektet Myndighed er en udvidelse til forretningsobjektet Organisation. En myndighed har en lovudøvende funktion. Kommunerne og store dele af den øvrige offentlige administration er offentlige myndigheder. Objektet Myndighed tilknyttes en Organisation 
# (The public authoirity)
type Myndighed {
    uuid: UUID!
    # Number, 3 or 4 digits, which identifies an authority.
    myndighedsKode: String!
}

#Forretningsobjektet Virksomhed er en udvidelse til Organisation, så der kan registreres et CVR-nummer, og dermed etableres en relation til CVR-registeret. En virksomhed er oprettet i CVR-registreret med et CVR-nummer, der efter opslag i CVR-registreret kan give adgang til oplysninger om virksomheden. Der registreres derfor alene CVR-nummer i Fælleskommunalt Organisationssystem.
# (The business as registered by The Danish business Authority)
type Virksomhed {
    uuid: UUID!
    # Number identifying the compagny
    cvrNummerTekst: CVR!
}

# what do we call this kind of relation where we have type, rolle and index ???
type KlassifikationRelation {
  type: UUID!
  rolle: UUID!
  indeks: String  
}

type Adresse {
  
  	uuid:  UUID!
  
    # Value from Klassification, eg. "Postadresse", "E-mail"  
    # If we can't obtain it from Klassification, it will be empty
    # There should be an error object with a warning in this case
   	adresseTitel: String 
	  adresseTekst:String!
    brugervendtNoegleTekst:String
  
    # Details from Klassifikation
   	klassifikation: KlassifikationRelation!    
}

# Forretningsobjektet OrganisationEnhed kan være et center, en afdeling, en sektion, et kontor, et team, en institiution eller lignende. Kommunens administrative organisation er opbygget af OrganisationEnheder.
#(The organisation unit)
type OrganisationEnhed {
    uuid: UUID!
    
    # Name of the Unit
    enhedNavn: String!
    # Brugervendt identifikation af objektet, dvs. identifikation fra kildesystemet for data

  	# Externally given key
    brugervendtNoegle: String

  	# The child nodes 
    underliggendeEnheder: [OrganisationEnhed!]!
    
  	# The parrent node
    overordnetEnhed: OrganisationEnhed
    
    # The state object
    tilstand: Tilstand!
    
  	# The Organization
    tilhoerer: Organisation!
  
  	adresser: [Adresse!]!
  
}

# The state of the object with a interval of when the state is in effect [fraTidspunkt, tilTidspunkt[ 
type Tilstand { 
    # The state of an object
    status: TilstandStatus!
    	
    # The state is in effect from - including the time. 
    fraTidspunkt: DateTime
  
    # The state is in effect to - excluding the time
    tilTidspunkt: DateTime 
}

# The valid states
enum TilstandStatus {
    AKTIV
    INAKTIV
}


# Forretningsobjektet Organisation repræsenterer en juridisk enhed. En kommune er et eksempel på en organisation. En organisation skal altid tilknyttes et virksomhedsobjekt og for myndigheders vedkommende et myndighedsobjekt. Dermed sikres, at CVR-nummer og eventuel myndighedskode kan føres tilbage til den gældende organisation.
#A legal entity, typically a municipality 
type Organisation {
    uuid: UUID!
  
   # Name of the Organisation
    organisationNavn: String!
    # Externally given key
    brugervendtNoegle: String!
    # Myndighed
    myndighed: Myndighed
    # Virksomhed
    virksomhed: Virksomhed!
    # The root entity
    organisationEnhed: OrganisationEnhed!
}


type Query {
  	
  	# If the root node is in the result, it is the first element of the list
    # adressTitle. Filter the adress list. 
   	organisationEnhedListe(cvr: CVR!, status: TilstandStatus!, adresseTitle:[String]): [OrganisationEnhed]
    organisationEnhed(uuid: UUID!): OrganisationEnhed 
  	organisation(cvr: CVR!): Organisation
  
}


scalar CVR
scalar UUID
# https://en.wikipedia.org/wiki/ISO_8601 
scalar DateTime
